spring.datasource.url=jdbc:postgresql://dpg-d78nk3n5r7bs73f9b11g-a.singapore-postgres.render.com:5432/demo3_9o2y
spring.datasource.username=demo3_9o2y_user
spring.datasource.password=z3fIGx0EM1rPqA6oZVM3HoGF2Vi8f3vX

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
server.id=1

 